## Build a Poisson distribution predictor

Dự đoán số lần khách hàng ghé thăm cửa hàng thông qua các chỉ số còn lại

In [33]:
import pandas as pd
df = pd.read_csv("..\\dataset\\poisson_visits.csv")
df.head()

   temperature  is_weekend  promo  rain  ad_spend  visits
0         31.2           0      0     0      5.86       3
1         25.8           1      0     1      7.81       5
2         33.0           0      0     1      3.77       3
3         33.8           0      1     1      0.12       5
4         22.2           1      1     0      5.10      12

In [34]:
# Data preprocessing
df['temperature'] = df['temperature'] - 30
df.head()

   temperature  is_weekend  promo  rain  ad_spend  visits
0          1.2           0      0     0      5.86       3
1         -4.2           1      0     1      7.81       5
2          3.0           0      0     1      3.77       3
3          3.8           0      1     1      0.12       5
4         -7.8           1      1     0      5.10      12

In [35]:
# Modeling

import numpy as np

X = df.drop(columns = ["visits"]).to_numpy()
X = np.column_stack((np.ones(X.shape[0]), X)) # (n, d)

y = df[["visits"]].to_numpy() # (n, 1)

print(y.shape, X.shape)

(1000, 1) (1000, 6)

In [ ]:
# Mini-batch gradient descent
learning_rate = 0.001
theta = np.zeros(X.shape[1]) 
theta = theta.reshape(-1, 1) # (d, 1)
epoch = 10000
mini_batch = 1000 # GD

for _ in range(epoch):
    start = 0
    while start <= X.shape[0] - 1:
        end = min(X.shape[0], start + mini_batch)
        x_now = X[start:end, :]
        y_now = y[start:end]

        y_pred = np.exp(x_now @ theta).reshape(-1, 1)

        gradient = (x_now.T @ (y_now - y_pred)).reshape(-1, 1)

        theta += learning_rate * gradient / (end - start)

        start = end

print(theta)

[[ 0.91849235]
 [ 0.02565332]
 [ 0.44699151]
 [ 0.39264801]
 [-0.29252153]
 [ 0.05139665]]

In [68]:
b = X[18]
print(b)
print(np.exp(b @ theta))

[1.  3.5 0.  0.  1.  9.5]
[3.33350931]

## Build a Bernouli distribution predictor